name: Check HDMF Dev Compatibility

on: [pull_request, workflow_dispatch]

jobs:
  validate:
    runs-on: ubuntu-latest
    steps:
      - name: Cancel non-latest runs
        uses: styfle/cancel-workflow-action@0.11.0
        with:
          all_but_latest: true
          access_token: ${{ github.token }}
      - uses: actions/checkout@v4
        with:
          ref: ${{ github.ref }} # checkout branch
      - name: Set up Python 3.11
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Clone HDMF and Run HDMF tests
        run: |
          git clone https://github.com/hdmf-dev/hdmf.git --recurse-submodules
          cd hdmf
          python -m pip install -r requirements-dev.txt -r requirements.txt
          python -m pip install -e .
          pytest tests/unit/common/
